version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9999:9999"
    env_file:
      - .env.local
    command: pnpm dev
    volumes:
      - .:/src
      - /src/node_modules